### ISSUE TITLE
이게머임

### ISSUE THREAD

**Issue by pjc0247** [OnionLee/Excel2JsonConverter#1]
https://github.com/OnionLee/Excel2JsonConverter/blob/master/Excel2JsonConverter/src/Table.cs#L72

특히이거

**Comment by OnionLee** [comment]
???

**Comment by pjc0247** [comment]
datas

**Comment by OnionLee** [comment]
ㅈㅅ 제가 영알못이라 data가 복수형이긴 한데 구분하려고 s붙인거
2015. 12. 1. 오후 2:39에 "Park June Chul" notifications@github.com님이 작성:

**Comment by pjc0247** [comment]
https://github.com/OnionLee/Excel2JsonConverter/blob/master/Excel2JsonConverter/src/Table.cs#L122

이건모임

**Comment by OnionLee** [comment]
저한테 왜그러심 ㅠㅠ

2015-12-01 16:23 GMT+09:00 Park June Chul notifications@github.com:

**Comment by pjc0247** [comment]
wt
